version: '3.3'
services:
  postgres:
    container_name: 'postgres-snobbin-db'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: snobbin
    ports:
      - '5434:5432'
    volumes:
      - postgresdata:/var/lib/postgresql/data
  
volumes:
  postgresdata: